// GENERATED FILE — do not edit by hand.
// Source of truth: presets/presets.json
// Regenerate with: python3 tools/gen_presets_header.py
#pragma once

namespace cinegrade {

struct PresetDef {
    const char* name;
    float exposure;
    float temperature;
    float tint;
    float contrast;
    float pivot;
    float shadows;
    float highlights;
    float whites;
    float blacks;
    float filmic_amount;
    float toe;
    float shoulder;
    float white_point;
    float saturation;
    float vibrance;
    float split_shadow_hue;
    float split_shadow_sat;
    float split_highlight_hue;
    float split_highlight_sat;
    float split_balance;
    float softness;
    float glow_amount;
    float glow_threshold;
    float glow_radius;
    float halation_amount;
    float halation_threshold;
    float halation_radius;
    float halation_hue;
    float ca_amount;
    float vignette_amount;
    float vignette_size;
    float vignette_feather;
    float vignette_roundness;
    float grain_amount;
    float grain_size;
    float grain_chroma;
    float grain_response;
    float gate_weave;
    float flicker;
    float lift[3];
    float gamma[3];
    float gain[3];
    float band_sat[6];
    float band_lum[6];
};

static const PresetDef kPresets[] = {
    { "None (Custom)",
      /*           exposure */ 0.0f,
      /*        temperature */ 0.0f,
      /*               tint */ 0.0f,
      /*           contrast */ 0.0f,
      /*              pivot */ 0.18f,
      /*            shadows */ 0.0f,
      /*         highlights */ 0.0f,
      /*             whites */ 0.0f,
      /*             blacks */ 0.0f,
      /*      filmic_amount */ 0.0f,
      /*                toe */ 0.0f,
      /*           shoulder */ 50.0f,
      /*        white_point */ 1.0f,
      /*         saturation */ 100.0f,
      /*           vibrance */ 0.0f,
      /*   split_shadow_hue */ 220.0f,
      /*   split_shadow_sat */ 0.0f,
      /* split_highlight_hue */ 45.0f,
      /* split_highlight_sat */ 0.0f,
      /*      split_balance */ 0.0f,
      /*           softness */ 0.0f,
      /*        glow_amount */ 0.0f,
      /*     glow_threshold */ 75.0f,
      /*        glow_radius */ 40.0f,
      /*    halation_amount */ 0.0f,
      /* halation_threshold */ 80.0f,
      /*    halation_radius */ 60.0f,
      /*       halation_hue */ 20.0f,
      /*          ca_amount */ 0.0f,
      /*    vignette_amount */ 0.0f,
      /*      vignette_size */ 70.0f,
      /*   vignette_feather */ 50.0f,
      /* vignette_roundness */ 0.0f,
      /*       grain_amount */ 0.0f,
      /*         grain_size */ 1.0f,
      /*       grain_chroma */ 20.0f,
      /*     grain_response */ 60.0f,
      /*         gate_weave */ 0.0f,
      /*            flicker */ 0.0f,
      /*               lift */ { 0.0f, 0.0f, 0.0f },
      /*              gamma */ { 1.0f, 1.0f, 1.0f },
      /*               gain */ { 1.0f, 1.0f, 1.0f },
      /*           band_sat */ { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
      /*           band_lum */ { 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f },
    },
    { "'80s Analog",
      /*           exposure */ 0.0f,
      /*        temperature */ 6.0f,
      /*               tint */ 2.0f,
      /*           contrast */ -8.0f,
      /*              pivot */ 0.18f,
      /*            shadows */ 12.0f,
      /*         highlights */ -20.0f,
      /*             whites */ -12.0f,
      /*             blacks */ 8.0f,
      /*      filmic_amount */ 85.0f,
      /*                toe */ 22.0f,
      /*           shoulder */ 70.0f,
      /*        white_point */ 1.12f,
      /*         saturation */ 74.0f,
      /*           vibrance */ -8.0f,
      /*   split_shadow_hue */ 215.0f,
      /*   split_shadow_sat */ 7.0f,
      /* split_highlight_hue */ 42.0f,
      /* split_highlight_sat */ 5.0f,
      /*      split_balance */ -10.0f,
      /*           softness */ 32.0f,
      /*        glow_amount */ 8.0f,
      /*     glow_threshold */ 78.0f,
      /*        glow_radius */ 55.0f,
      /*    halation_amount */ 22.0f,
      /* halation_threshold */ 74.0f,
      /*    halation_radius */ 70.0f,
      /*       halation_hue */ 18.0f,
      /*          ca_amount */ 8.0f,
      /*    vignette_amount */ 14.0f,
      /*      vignette_size */ 78.0f,
      /*   vignette_feather */ 65.0f,
      /* vignette_roundness */ 0.0f,
      /*       grain_amount */ 42.0f,
      /*         grain_size */ 0.85f,
      /*       grain_chroma */ 30.0f,
      /*     grain_response */ 65.0f,
      /*         gate_weave */ 12.0f,
      /*            flicker */ 4.0f,
      /*               lift */ { 0.01f, 0.012f, 0.016f },
      /*              gamma */ { 1.0f, 1.0f, 1.0f },
      /*               gain */ { 0.985f, 0.985f, 0.975f },
      /*           band_sat */ { -6.0f, 4.0f, -12.0f, -10.0f, -4.0f, -10.0f },
      /*           band_lum */ { 0.0f, 2.0f, -4.0f, 0.0f, 0.0f, 0.0f },
    },
    { "Wes Pastel",
      /*           exposure */ 0.18f,
      /*        temperature */ 12.0f,
      /*               tint */ 3.0f,
      /*           contrast */ -14.0f,
      /*              pivot */ 0.18f,
      /*            shadows */ 18.0f,
      /*         highlights */ -10.0f,
      /*             whites */ 0.0f,
      /*             blacks */ 10.0f,
      /*      filmic_amount */ 60.0f,
      /*                toe */ 8.0f,
      /*           shoulder */ 55.0f,
      /*        white_point */ 1.06f,
      /*         saturation */ 112.0f,
      /*           vibrance */ 22.0f,
      /*   split_shadow_hue */ 190.0f,
      /*   split_shadow_sat */ 6.0f,
      /* split_highlight_hue */ 48.0f,
      /* split_highlight_sat */ 12.0f,
      /*      split_balance */ 12.0f,
      /*           softness */ 8.0f,
      /*        glow_amount */ 6.0f,
      /*     glow_threshold */ 82.0f,
      /*        glow_radius */ 35.0f,
      /*    halation_amount */ 6.0f,
      /* halation_threshold */ 85.0f,
      /*    halation_radius */ 50.0f,
      /*       halation_hue */ 20.0f,
      /*          ca_amount */ 0.0f,
      /*    vignette_amount */ 10.0f,
      /*      vignette_size */ 82.0f,
      /*   vignette_feather */ 70.0f,
      /* vignette_roundness */ 0.0f,
      /*       grain_amount */ 14.0f,
      /*         grain_size */ 0.7f,
      /*       grain_chroma */ 10.0f,
      /*     grain_response */ 55.0f,
      /*         gate_weave */ 4.0f,
      /*            flicker */ 1.5f,
      /*               lift */ { 0.008f, 0.008f, 0.006f },
      /*              gamma */ { 1.0f, 1.0f, 1.0f },
      /*               gain */ { 1.01f, 1.0f, 0.97f },
      /*           band_sat */ { 10.0f, 34.0f, 6.0f, 14.0f, 2.0f, 6.0f },
      /*           band_lum */ { 2.0f, 8.0f, 2.0f, 2.0f, -2.0f, 0.0f },
    },
    { "Blockbuster",
      /*           exposure */ 0.0f,
      /*        temperature */ 4.0f,
      /*               tint */ 0.0f,
      /*           contrast */ 16.0f,
      /*              pivot */ 0.18f,
      /*            shadows */ -6.0f,
      /*         highlights */ -14.0f,
      /*             whites */ 0.0f,
      /*             blacks */ -6.0f,
      /*      filmic_amount */ 90.0f,
      /*                toe */ 18.0f,
      /*           shoulder */ 60.0f,
      /*        white_point */ 1.15f,
      /*         saturation */ 104.0f,
      /*           vibrance */ 14.0f,
      /*   split_shadow_hue */ 195.0f,
      /*   split_shadow_sat */ 16.0f,
      /* split_highlight_hue */ 35.0f,
      /* split_highlight_sat */ 8.0f,
      /*      split_balance */ -6.0f,
      /*           softness */ 6.0f,
      /*        glow_amount */ 10.0f,
      /*     glow_threshold */ 80.0f,
      /*        glow_radius */ 45.0f,
      /*    halation_amount */ 8.0f,
      /* halation_threshold */ 82.0f,
      /*    halation_radius */ 55.0f,
      /*       halation_hue */ 20.0f,
      /*          ca_amount */ 4.0f,
      /*    vignette_amount */ 18.0f,
      /*      vignette_size */ 75.0f,
      /*   vignette_feather */ 60.0f,
      /* vignette_roundness */ 0.0f,
      /*       grain_amount */ 16.0f,
      /*         grain_size */ 0.8f,
      /*       grain_chroma */ 12.0f,
      /*     grain_response */ 60.0f,
      /*         gate_weave */ 0.0f,
      /*            flicker */ 0.0f,
      /*               lift */ { 0.0f, 0.0f, 0.0f },
      /*              gamma */ { 1.0f, 1.0f, 1.0f },
      /*               gain */ { 1.0f, 1.0f, 1.0f },
      /*           band_sat */ { 12.0f, 6.0f, -14.0f, 10.0f, 0.0f, -6.0f },
      /*           band_lum */ { 2.0f, 2.0f, -6.0f, -2.0f, -4.0f, 0.0f },
    },
    { "Kodachrome 64",
      /*           exposure */ -0.08f,
      /*        temperature */ 10.0f,
      /*               tint */ 4.0f,
      /*           contrast */ 20.0f,
      /*              pivot */ 0.18f,
      /*            shadows */ -8.0f,
      /*         highlights */ -8.0f,
      /*             whites */ -4.0f,
      /*             blacks */ -12.0f,
      /*      filmic_amount */ 95.0f,
      /*                toe */ 30.0f,
      /*           shoulder */ 65.0f,
      /*        white_point */ 1.1f,
      /*         saturation */ 116.0f,
      /*           vibrance */ 10.0f,
      /*   split_shadow_hue */ 230.0f,
      /*   split_shadow_sat */ 5.0f,
      /* split_highlight_hue */ 45.0f,
      /* split_highlight_sat */ 7.0f,
      /*      split_balance */ 0.0f,
      /*           softness */ 0.0f,
      /*        glow_amount */ 4.0f,
      /*     glow_threshold */ 85.0f,
      /*        glow_radius */ 30.0f,
      /*    halation_amount */ 12.0f,
      /* halation_threshold */ 80.0f,
      /*    halation_radius */ 45.0f,
      /*       halation_hue */ 15.0f,
      /*          ca_amount */ 3.0f,
      /*    vignette_amount */ 12.0f,
      /*      vignette_size */ 80.0f,
      /*   vignette_feather */ 55.0f,
      /* vignette_roundness */ 0.0f,
      /*       grain_amount */ 24.0f,
      /*         grain_size */ 0.75f,
      /*       grain_chroma */ 25.0f,
      /*     grain_response */ 62.0f,
      /*         gate_weave */ 6.0f,
      /*            flicker */ 2.0f,
      /*               lift */ { 0.0f, 0.0f, 0.0f },
      /*              gamma */ { 1.0f, 1.0f, 1.0f },
      /*               gain */ { 1.015f, 1.0f, 0.97f },
      /*           band_sat */ { 26.0f, 12.0f, -6.0f, -8.0f, 8.0f, 4.0f },
      /*           band_lum */ { -4.0f, 2.0f, -6.0f, -4.0f, -8.0f, -4.0f },
    },
    { "Bleach Noir",
      /*           exposure */ -0.05f,
      /*        temperature */ -8.0f,
      /*               tint */ -2.0f,
      /*           contrast */ 30.0f,
      /*              pivot */ 0.18f,
      /*            shadows */ -10.0f,
      /*         highlights */ -6.0f,
      /*             whites */ 4.0f,
      /*             blacks */ -16.0f,
      /*      filmic_amount */ 100.0f,
      /*                toe */ 35.0f,
      /*           shoulder */ 45.0f,
      /*        white_point */ 1.2f,
      /*         saturation */ 46.0f,
      /*           vibrance */ -10.0f,
      /*   split_shadow_hue */ 215.0f,
      /*   split_shadow_sat */ 8.0f,
      /* split_highlight_hue */ 200.0f,
      /* split_highlight_sat */ 3.0f,
      /*      split_balance */ -8.0f,
      /*           softness */ 4.0f,
      /*        glow_amount */ 6.0f,
      /*     glow_threshold */ 84.0f,
      /*        glow_radius */ 40.0f,
      /*    halation_amount */ 6.0f,
      /* halation_threshold */ 86.0f,
      /*    halation_radius */ 50.0f,
      /*       halation_hue */ 25.0f,
      /*          ca_amount */ 5.0f,
      /*    vignette_amount */ 26.0f,
      /*      vignette_size */ 70.0f,
      /*   vignette_feather */ 55.0f,
      /* vignette_roundness */ 0.0f,
      /*       grain_amount */ 48.0f,
      /*         grain_size */ 1.15f,
      /*       grain_chroma */ 8.0f,
      /*     grain_response */ 70.0f,
      /*         gate_weave */ 8.0f,
      /*            flicker */ 3.0f,
      /*               lift */ { 0.0f, 0.0f, 0.0f },
      /*              gamma */ { 1.0f, 1.0f, 1.0f },
      /*               gain */ { 1.0f, 1.0f, 1.0f },
      /*           band_sat */ { 6.0f, -10.0f, -20.0f, -10.0f, 0.0f, -10.0f },
      /*           band_lum */ { 0.0f, 0.0f, -8.0f, -4.0f, -6.0f, -4.0f },
    },
    { "Neon Night",
      /*           exposure */ 0.12f,
      /*        temperature */ -10.0f,
      /*               tint */ 6.0f,
      /*           contrast */ 8.0f,
      /*              pivot */ 0.18f,
      /*            shadows */ 22.0f,
      /*         highlights */ -18.0f,
      /*             whites */ 0.0f,
      /*             blacks */ 6.0f,
      /*      filmic_amount */ 88.0f,
      /*                toe */ 15.0f,
      /*           shoulder */ 72.0f,
      /*        white_point */ 1.18f,
      /*         saturation */ 108.0f,
      /*           vibrance */ 16.0f,
      /*   split_shadow_hue */ 225.0f,
      /*   split_shadow_sat */ 14.0f,
      /* split_highlight_hue */ 320.0f,
      /* split_highlight_sat */ 8.0f,
      /*      split_balance */ -4.0f,
      /*           softness */ 14.0f,
      /*        glow_amount */ 26.0f,
      /*     glow_threshold */ 68.0f,
      /*        glow_radius */ 65.0f,
      /*    halation_amount */ 28.0f,
      /* halation_threshold */ 70.0f,
      /*    halation_radius */ 85.0f,
      /*       halation_hue */ 12.0f,
      /*          ca_amount */ 12.0f,
      /*    vignette_amount */ 22.0f,
      /*      vignette_size */ 72.0f,
      /*   vignette_feather */ 65.0f,
      /* vignette_roundness */ 0.0f,
      /*       grain_amount */ 30.0f,
      /*         grain_size */ 0.9f,
      /*       grain_chroma */ 22.0f,
      /*     grain_response */ 68.0f,
      /*         gate_weave */ 6.0f,
      /*            flicker */ 2.5f,
      /*               lift */ { 0.006f, 0.008f, 0.014f },
      /*              gamma */ { 1.0f, 1.0f, 1.0f },
      /*               gain */ { 1.0f, 1.0f, 1.0f },
      /*           band_sat */ { 8.0f, -6.0f, -10.0f, 18.0f, 14.0f, 20.0f },
      /*           band_lum */ { 0.0f, -2.0f, -6.0f, 4.0f, 2.0f, 4.0f },
    },
    { "Arrakis 65",
      /*           exposure */ -0.05f,
      /*        temperature */ 14.0f,
      /*               tint */ 3.0f,
      /*           contrast */ 18.0f,
      /*              pivot */ 0.18f,
      /*            shadows */ -6.0f,
      /*         highlights */ -12.0f,
      /*             whites */ -6.0f,
      /*             blacks */ -10.0f,
      /*      filmic_amount */ 95.0f,
      /*                toe */ 26.0f,
      /*           shoulder */ 62.0f,
      /*        white_point */ 1.12f,
      /*         saturation */ 118.0f,
      /*           vibrance */ 12.0f,
      /*   split_shadow_hue */ 230.0f,
      /*   split_shadow_sat */ 8.0f,
      /* split_highlight_hue */ 42.0f,
      /* split_highlight_sat */ 10.0f,
      /*      split_balance */ -4.0f,
      /*           softness */ 6.0f,
      /*        glow_amount */ 8.0f,
      /*     glow_threshold */ 80.0f,
      /*        glow_radius */ 45.0f,
      /*    halation_amount */ 14.0f,
      /* halation_threshold */ 78.0f,
      /*    halation_radius */ 55.0f,
      /*       halation_hue */ 16.0f,
      /*          ca_amount */ 3.0f,
      /*    vignette_amount */ 16.0f,
      /*      vignette_size */ 76.0f,
      /*   vignette_feather */ 60.0f,
      /* vignette_roundness */ 0.0f,
      /*       grain_amount */ 14.0f,
      /*         grain_size */ 1.0f,
      /*       grain_chroma */ 15.0f,
      /*     grain_response */ 60.0f,
      /*         gate_weave */ 3.0f,
      /*            flicker */ 1.0f,
      /*               lift */ { 0.004f, 0.004f, 0.006f },
      /*              gamma */ { 1.0f, 1.0f, 1.0f },
      /*               gain */ { 1.02f, 1.0f, 0.955f },
      /*           band_sat */ { 24.0f, 18.0f, -12.0f, -14.0f, 4.0f, 6.0f },
      /*           band_lum */ { 0.0f, 4.0f, -6.0f, -4.0f, -6.0f, -2.0f },
    },
    { "Eterna Soft",
      /*           exposure */ 0.0f,
      /*        temperature */ 2.0f,
      /*               tint */ -2.0f,
      /*           contrast */ -6.0f,
      /*              pivot */ 0.18f,
      /*            shadows */ 10.0f,
      /*         highlights */ -16.0f,
      /*             whites */ -8.0f,
      /*             blacks */ 4.0f,
      /*      filmic_amount */ 80.0f,
      /*                toe */ 14.0f,
      /*           shoulder */ 68.0f,
      /*        white_point */ 1.1f,
      /*         saturation */ 88.0f,
      /*           vibrance */ 6.0f,
      /*   split_shadow_hue */ 200.0f,
      /*   split_shadow_sat */ 5.0f,
      /* split_highlight_hue */ 50.0f,
      /* split_highlight_sat */ 4.0f,
      /*      split_balance */ 0.0f,
      /*           softness */ 12.0f,
      /*        glow_amount */ 5.0f,
      /*     glow_threshold */ 82.0f,
      /*        glow_radius */ 40.0f,
      /*    halation_amount */ 10.0f,
      /* halation_threshold */ 80.0f,
      /*    halation_radius */ 55.0f,
      /*       halation_hue */ 20.0f,
      /*          ca_amount */ 2.0f,
      /*    vignette_amount */ 10.0f,
      /*      vignette_size */ 80.0f,
      /*   vignette_feather */ 65.0f,
      /* vignette_roundness */ 0.0f,
      /*       grain_amount */ 18.0f,
      /*         grain_size */ 0.8f,
      /*       grain_chroma */ 15.0f,
      /*     grain_response */ 60.0f,
      /*         gate_weave */ 4.0f,
      /*            flicker */ 1.0f,
      /*               lift */ { 0.0f, 0.0f, 0.0f },
      /*              gamma */ { 1.0f, 1.0f, 1.0f },
      /*               gain */ { 1.0f, 1.0f, 1.0f },
      /*           band_sat */ { -4.0f, 0.0f, -8.0f, -6.0f, -2.0f, -4.0f },
      /*           band_lum */ { 0.0f, 2.0f, -2.0f, 0.0f, -2.0f, 0.0f },
    },
};

static const int kNumPresets = 9;

static const char* kPresetPopupString = "None (Custom)|'80s Analog|Wes Pastel|Blockbuster|Kodachrome 64|Bleach Noir|Neon Night|Arrakis 65|Eterna Soft";

} // namespace cinegrade
